name: core_framework
description: Core abstractions and environment models for skeleton-based apps.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  injectable: ^2.5.1
  retrofit: ^4.9.2
